sudo: required
services: 
    - docker

before_install:
    - docker build -t xlreon/react-docker -f Dockerfile.dev .

script:
    - docker run xlreon/react-docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "react-docker"
    env: "ReactDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-952941133223"
    bucket_path: "react-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY 
